[package]
name = "adb"
version = "0.4.0"
edition = "2021"
authors = ["J/A <archer884@gmail.com>"]
description = "An airport code database and nav assist"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"

[dependencies]
atty = "0.2.14"
clap = { version = "4.3.21", features = ["derive", "wrap_help" ] }
csv = "1.2.2"
directories = "5.0.1"
geoutils = "0.5.1"
hashbrown = "0.14.0"
regex = "1.9.3"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tantivy = "0.20.2"
