[package]
name = "adb"
version = "0.4.4"
edition = "2024"
authors = ["J/A <archer884@gmail.com>"]
description = "An airport code database and nav assist"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = 0

[dependencies]
bitcode = "0.6"
clap = { version = "4.6.4", features = ["derive", "wrap_help"] }
csv = "1.4.0"
directories = "6.0.0"
fst = { version = "0.4", features = ["levenshtein"] }
geoutils = "0.5.1"
hashbrown = "0.17.1"
latlon = "0.1.3"
redb = "4"
serde = { version = "1.0.229", features = ["derive"] }
