[package]
name = "adb"
version = "0.1.1"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adb-data = { git = "https://github.com/archer884/adb-data.git" }
clap = "2.33.3"
hashbrown = "0.9.1"
regex = "1.3.9"

[build-dependencies]
adb-data = { git = "https://github.com/archer884/adb-data.git", features = ["aotload"] }
csv = "1.1.3"
