[package]
name = "adb"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
csv = "1.1.3"
geoutils = "0.4.0"
hashbrown = "0.9.0"
serde = { version = "1.0.116", features = ["derive"] }
