[package]
name = "adb"
version = "0.3.2"
edition = "2021"
authors = ["J/A <archer884@gmail.com>"]
description = "An airport code database and nav assist"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.1.4", features = ["derive", "wrap_help" ] }
csv = "1.1.6"
directories = "4.0.1"
geoutils = "0.5.1"
hashbrown = "0.13.2"
libflate = "1.2.0"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
tantivy = "0.19.1"
