[package]
name = "adb"
version = "0.1.4"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"
description = "An airport code database and nav assist"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
atty = "0.2.14"

[dependencies.adb-data]
git = "https://github.com/archer884/adb-data.git"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["wrap_help"]

[build-dependencies]
csv = "1.1.5"

[build-dependencies.adb-data]
git = "https://github.com/archer884/adb-data.git"
features = ["aotload"]
